-- MySQL Script generated by MySQL Workbench
-- Sun Jun  8 17:11:22 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `AreaComum`
-- -----------------------------------------------------
create database condominio;
use condominio;

CREATE TABLE IF NOT EXISTS `AreaComum` (
  `IdAreaComum` INT NOT NULL AUTO_INCREMENT,
  `nomeArea` VARCHAR(200) NOT NULL,
  `descArea` VARCHAR(300),
  `regra` VARCHAR(300),
  `capacidadePessoas` INT NOT NULL,
  `aceitaAnimais` TINYINT NOT NULL,
  PRIMARY KEY (`IdAreaComum`)
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `Pessoa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pessoa` (
  `IdPessoa` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `CPF` VARCHAR(14) NOT NULL,
  `dataNascimento` DATE NOT NULL,
  `telefone` VARCHAR(20) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`IdPessoa`),
  UNIQUE INDEX `CPF_UNIQUE` (`CPF`)
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `Morador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Morador` (
  `IdMorador` INT NOT NULL AUTO_INCREMENT,
  `tipoVinculo` ENUM('Proprietário', 'Inquilino', 'Dependente', 'Outro') NOT NULL DEFAULT 'Outro',
  `dataInicio` DATE NOT NULL,
  `dataFim` DATE DEFAULT NULL,
  `Pessoa_idPessoa` INT NOT NULL,
  PRIMARY KEY (`IdMorador`),
  INDEX `fk_Morador_Pessoa1_idx` (`Pessoa_idPessoa`),
  CONSTRAINT `fk_Morador_Pessoa1`
    FOREIGN KEY (`Pessoa_idPessoa`) REFERENCES `Pessoa` (`IdPessoa`)
    ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `Sindico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Sindico` (
  `IdSindico` INT NOT NULL AUTO_INCREMENT,
  `dataPosse` DATE NOT NULL,
  `dataFim` DATE DEFAULT NULL,
  `Pessoa_idPessoa` INT NOT NULL,
  PRIMARY KEY (`IdSindico`),
  INDEX `fk_Sindico_Pessoa1_idx` (`Pessoa_idPessoa`),
  CONSTRAINT `fk_Sindico_Pessoa1`
    FOREIGN KEY (`Pessoa_idPessoa`) REFERENCES `Pessoa` (`IdPessoa`)
    ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `Reserva`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Reserva` (
  `IdReserva` INT NOT NULL AUTO_INCREMENT,
  `AreaComum_IdAreaComum` INT NOT NULL,
  `Morador_IdMorador` INT NOT NULL,
  `dataReserva` DATE NOT NULL,
  `motivoReserva` VARCHAR(255) NOT NULL,
  `horaInicio` TIME NOT NULL,
  `horaTermino` TIME DEFAULT NULL,
  PRIMARY KEY (`IdReserva`),
  UNIQUE INDEX `uq_Reserva_AreaDataHoraInicio` (`AreaComum_IdAreaComum`, `dataReserva`, `horaInicio`),
  INDEX `fk_Reserva_AreaComum_idx` (`AreaComum_IdAreaComum`),
  INDEX `fk_Reserva_Morador_idx` (`Morador_IdMorador`),
  CONSTRAINT `fk_Reserva_AreaComum`
    FOREIGN KEY (`AreaComum_IdAreaComum`) REFERENCES `AreaComum` (`IdAreaComum`)
    ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reserva_Morador`
    FOREIGN KEY (`Morador_IdMorador`) REFERENCES `Morador` (`IdMorador`)
    ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `Ocorrencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Ocorrencia` (
  `IdOcorrencia` INT NOT NULL AUTO_INCREMENT,
  `tituloOcorrencia` VARCHAR(255) NOT NULL,
  `descOcorrencia` TEXT NOT NULL,
  `dataOcorrencia` DATE NOT NULL,
  PRIMARY KEY (`IdOcorrencia`)
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `EnvolvimentoOcorrencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EnvolvimentoOcorrencia` (
  `Ocorrencia_IdOcorrencia` INT NOT NULL,
  `Pessoa_IdPessoa` INT NOT NULL,
  `descEnvolvimento` TEXT NOT NULL,
  PRIMARY KEY (`Ocorrencia_IdOcorrencia`, `Pessoa_IdPessoa`),
  INDEX `fk_EnvolvimentoOcorrencia_Ocorrencia1_idx` (`Ocorrencia_IdOcorrencia`),
  INDEX `fk_EnvolvimentoOcorrencia_Pessoa1_idx` (`Pessoa_IdPessoa`),
  CONSTRAINT `fk_EnvolvimentoOcorrencia_Ocorrencia1`
    FOREIGN KEY (`Ocorrencia_IdOcorrencia`) REFERENCES `Ocorrencia` (`IdOcorrencia`)
    ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_EnvolvimentoOcorrencia_Pessoa1`
    FOREIGN KEY (`Pessoa_IdPessoa`) REFERENCES `Pessoa` (`IdPessoa`)
    ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `Comunicado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Comunicado` (
  `idComunicado` INT NOT NULL AUTO_INCREMENT,
  `tituloComunicado` VARCHAR(255) NOT NULL,
  `descComunicado` TEXT NOT NULL,
  `data` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `Sindico_IdSindico` INT NOT NULL,
  PRIMARY KEY (`idComunicado`),
  INDEX `fk_Comunicado_Sindico1_idx` (`Sindico_IdSindico`),
  CONSTRAINT `fk_Comunicado_Sindico1`
    FOREIGN KEY (`Sindico_IdSindico`) REFERENCES `Sindico` (`IdSindico`)
    ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `AtaAssembleia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AtaAssembleia` (
  `IdAtaAssembleia` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(255) NOT NULL,
  `descAta` TEXT NOT NULL,
  `dataAssembleia` DATE NOT NULL,
  `Sindico_IdSindico` INT NOT NULL,
  PRIMARY KEY (`IdAtaAssembleia`),
  INDEX `fk_AtaAssembleia_Sindico1_idx` (`Sindico_IdSindico`),
  CONSTRAINT `fk_AtaAssembleia_Sindico1`
    FOREIGN KEY (`Sindico_IdSindico`) REFERENCES `Sindico` (`IdSindico`)
    ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `Enquete`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Enquete` (
  `IdEnquete` INT NOT NULL AUTO_INCREMENT,
  `Sindico_IdSindico` INT NOT NULL,
  `questao` VARCHAR(255) NOT NULL,
  `dataInicio` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `dataFim` DATETIME NOT NULL,
  `totalParticipantes` INT DEFAULT NULL,
  PRIMARY KEY (`IdEnquete`),
  INDEX `fk_Enquete_Sindico1_idx` (`Sindico_IdSindico`),
  CONSTRAINT `fk_Enquete_Sindico1`
    FOREIGN KEY (`Sindico_IdSindico`) REFERENCES `Sindico` (`IdSindico`)
    ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `Opcao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Opcao` (
  `IdOpcao` INT NOT NULL AUTO_INCREMENT,
  `tituloOpcao` VARCHAR(255) NOT NULL,
  `Enquete_IdEnquete` INT NOT NULL,
  `porcentResposta` DECIMAL(10,3) DEFAULT NULL,
  PRIMARY KEY (`IdOpcao`),
  INDEX `fk_Opcao_Enquete1_idx` (`Enquete_IdEnquete`),
  CONSTRAINT `fk_Opcao_Enquete1`
    FOREIGN KEY (`Enquete_IdEnquete`) REFERENCES `Enquete` (`IdEnquete`)
    ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `Taxa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Taxa` (
  `IdTaxa` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(255) NOT NULL,
  `vencimento` DATETIME NOT NULL,
  `emissao` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `valorCobrado` DECIMAL(10,2) NOT NULL,
  `descricao` TEXT,
  PRIMARY KEY (`IdTaxa`)
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `Transacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Transacao` (
  `IdTransacao` INT NOT NULL AUTO_INCREMENT,
  `data` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `valorPago` DECIMAL(10,2) NOT NULL,
  `formaPagamento` ENUM('Pix', 'Crédito', 'Debito', 'Boleto', 'Dinheiro em espécie', 'Outro') NOT NULL DEFAULT 'Outro',
  `Taxa_IdTaxa` INT NOT NULL,
  `Morador_IdMorador` INT NOT NULL,
  PRIMARY KEY (`IdTransacao`),
  INDEX `fk_Transacao_Taxa1_idx` (`Taxa_IdTaxa`),
  INDEX `fk_Transacao_Morador1_idx` (`Morador_IdMorador`),
  CONSTRAINT `fk_Transacao_Taxa1`
    FOREIGN KEY (`Taxa_IdTaxa`) REFERENCES `Taxa` (`IdTaxa`)
    ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_Transacao_Morador1`
    FOREIGN KEY (`Morador_IdMorador`) REFERENCES `Morador` (`IdMorador`)
    ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `Voto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Voto` (
  `Morador_IdMorador` INT NOT NULL,
  `Opcao_IdOpcao` INT NOT NULL,
  `dataVoto` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`Morador_IdMorador`, `Opcao_IdOpcao`),
  INDEX `fk_Voto_Opcao_idx` (`Opcao_IdOpcao`),
  INDEX `fk_Voto_Morador_idx` (`Morador_IdMorador`),
  CONSTRAINT `fk_Voto_Morador`
    FOREIGN KEY (`Morador_IdMorador`) REFERENCES `Morador` (`IdMorador`)
    ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_Voto_Opcao`
    FOREIGN KEY (`Opcao_IdOpcao`) REFERENCES `Opcao` (`IdOpcao`)
    ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;